#!/bin/bash
GDB=
#GDB="gdb --args"

# run it twice, once without, once with pyc files.
make -j36 all pycremoval && \
    $GDB ./python -E -tt -Wd -3 -m test.regrtest -v test_future_encoding && \
    $GDB ./python -E -tt -Wd -3 -m test.regrtest -v test_future_encoding
