#!/bin/bash
GDB=
#GDB="gdb --args"

# run it twice, once without, once with pyc files.
make -j36 all pycremoval && \
    $GDB ./python Lib/test/regrtest.py -v test_future_encoding \
    $GDB ./python Lib/test/regrtest.py -v test_future_encoding
